### ISSUE TITLE
Investigate whether the PublicKey in the TransactionOutput is redundant (and remove it if this is the case)

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-protobuf#114]

**Comment by autholykos** [comment]
This seems to extend to the `value` field as well

**Comment by autholykos** [comment]
aaaaaand to the blinder. Looks like the whole Transaction Output is redundant

**Comment by julesdesmit** [comment]
This issue has been obsoleted by the Phoenix re-write.
