### ISSUE TITLE
Rusk state transition and execution

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/dusk-protobuf#4]
For initial modeling, to be evolved

TransactionItem
* Sender - `[]byte`
* Recipient - `[]byte`
* Value - `fixed64`

Transaction
* Items - `[TransactionItem]
* Fee - `fixed64`

StateTransitionValidationRequest
* Txs - `[Transaction]`

StateTransitionValidationRespose
* Txs - `[Transaction]`
* Success - `bool`

StateTransitionExecutionRequest
* Txs - `[Transaction]`

StateTransitionExecutionRespose
* Txs - `[Transaction]`
* Success - `bool`

**Comment by vlopes11** [comment]
There is a bug with `tonic` that will complicate the creation of multi-package gRPC servers and clients.

The decision, for now, is to include the Rusk state transition validation within the phoenix package

**Comment by autholykos** [comment]
Closed with #32
