### ISSUE TITLE
Why does the TransactionInput carry a SecretKey field?

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-protobuf#58]
@julesdesmit @toghrulmaharramov

**Comment by julesdesmit** [comment]
The `TransactionInput` carries multiple items which are unnecessary for transmission - the structure in the Phoenix library can hold the secret key, the note etc. which is needed for creating the zk proof. However, this information should not leave the process the zk proof was created in, and thus these fields (including the secret key) should not exist on the protobuf structure.

I'll open a PR which removes the obsolete fields.
